#!/usr/bin/env bash
# A custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/termi56661 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
echo "Ceci n'est pas une page" > /var/www/html/my_404.html
sed -i "/server_name _;/a error_page 404 /my_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
